// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiqnbtcBmQbggUr82zGmXKVDKUhVCkrpg',
    appId: '1:374090990024:web:02db0d5716834542cf80fd',
    messagingSenderId: '374090990024',
    projectId: 'dawinreal2001',
    authDomain: 'dawinreal2001.firebaseapp.com',
    storageBucket: 'dawinreal2001.appspot.com',
    measurementId: 'G-18XFS8XSMS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdMsVM3osiMfJWbRTCmyjs5NzyyB-8_kQ',
    appId: '1:374090990024:android:78bebb5ed02e7527cf80fd',
    messagingSenderId: '374090990024',
    projectId: 'dawinreal2001',
    storageBucket: 'dawinreal2001.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPVq4xUY269VCAB5DWjJtBBve0G3cj_ug',
    appId: '1:374090990024:ios:9234b4d9dcdad514cf80fd',
    messagingSenderId: '374090990024',
    projectId: 'dawinreal2001',
    storageBucket: 'dawinreal2001.appspot.com',
    iosBundleId: 'com.example.dawinadmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPVq4xUY269VCAB5DWjJtBBve0G3cj_ug',
    appId: '1:374090990024:ios:9234b4d9dcdad514cf80fd',
    messagingSenderId: '374090990024',
    projectId: 'dawinreal2001',
    storageBucket: 'dawinreal2001.appspot.com',
    iosBundleId: 'com.example.dawinadmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDiqnbtcBmQbggUr82zGmXKVDKUhVCkrpg',
    appId: '1:374090990024:web:6d24bb8b6fb5c355cf80fd',
    messagingSenderId: '374090990024',
    projectId: 'dawinreal2001',
    authDomain: 'dawinreal2001.firebaseapp.com',
    storageBucket: 'dawinreal2001.appspot.com',
    measurementId: 'G-H3YNKH4TX8',
  );
}
